/*
 * WebAPI
 * Access Sponge powered Minecraft servers through a WebAPI  # Introduction This is the documentation of the various API routes offered by the WebAPI plugin.  This documentation assumes that you are familiar with the basic concepts of Web API's, such as `GET`, `PUT`, `POST` and `DELETE` methods, request `HEADERS` and `RESPONSE CODES` and `JSON` data.  By default this documentation can be found at http:/localhost:8080 (while your minecraft server is running) and the various routes start with http:/localhost:8080/api/...  As a quick test try reaching the route http:/localhost:8080/api/info (remember that you can only access \"localhost\" routes on the server on which you are running minecraft). This route should show you basic information about your server, like the motd and player count.  # Additional data Certain endpoints (such as `/player`, `/entity` and `/tile-entity` have additional properties which are not documented here, because the data depends on the concrete object type (eg. `Sheep` have a wool color, others do not) and on the other plugins/mods that are running on your server which might add additional data.  You can also find more information in the github docs (https:/github.com/Valandur/Web-API/tree/master/docs/DATA.md) 
 *
 * OpenAPI spec version: <version>
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.WebBook;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * WebBookFull
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-17T22:13:43.947+01:00")
public class WebBookFull {
  @SerializedName("id")
  private String id = null;

  @SerializedName("title")
  private String title = null;

  @SerializedName("lines")
  private List<String> lines = null;

  @SerializedName("html")
  private String html = null;

  public WebBookFull id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The id of the web books.
   * @return id
  **/
  @ApiModelProperty(value = "The id of the web books.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public WebBookFull title(String title) {
    this.title = title;
    return this;
  }

   /**
   * The title of the web book.
   * @return title
  **/
  @ApiModelProperty(value = "The title of the web book.")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public WebBookFull lines(List<String> lines) {
    this.lines = lines;
    return this;
  }

  public WebBookFull addLinesItem(String linesItem) {
    if (this.lines == null) {
      this.lines = new ArrayList<String>();
    }
    this.lines.add(linesItem);
    return this;
  }

   /**
   * The lines of text in the web book.
   * @return lines
  **/
  @ApiModelProperty(value = "The lines of text in the web book.")
  public List<String> getLines() {
    return lines;
  }

  public void setLines(List<String> lines) {
    this.lines = lines;
  }

  public WebBookFull html(String html) {
    this.html = html;
    return this;
  }

   /**
   * The html content of the book.
   * @return html
  **/
  @ApiModelProperty(value = "The html content of the book.")
  public String getHtml() {
    return html;
  }

  public void setHtml(String html) {
    this.html = html;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebBookFull webBookFull = (WebBookFull) o;
    return Objects.equals(this.id, webBookFull.id) &&
        Objects.equals(this.title, webBookFull.title) &&
        Objects.equals(this.lines, webBookFull.lines) &&
        Objects.equals(this.html, webBookFull.html);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, title, lines, html);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebBookFull {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    lines: ").append(toIndentedString(lines)).append("\n");
    sb.append("    html: ").append(toIndentedString(html)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

