/*
 * WebAPI
 * Access Sponge powered Minecraft servers through a WebAPI  # Introduction This is the documentation of the various API routes offered by the WebAPI plugin.  This documentation assumes that you are familiar with the basic concepts of Web API's, such as `GET`, `PUT`, `POST` and `DELETE` methods, request `HEADERS` and `RESPONSE CODES` and `JSON` data.  By default this documentation can be found at http:/localhost:8080 (while your minecraft server is running) and the various routes start with http:/localhost:8080/api/...  As a quick test try reaching the route http:/localhost:8080/api/info (remember that you can only access \"localhost\" routes on the server on which you are running minecraft). This route should show you basic information about your server, like the motd and player count.  # Additional data Certain endpoints (such as `/player`, `/entity` and `/tile-entity` have additional properties which are not documented here, because the data depends on the concrete object type (eg. `Sheep` have a wool color, others do not) and on the other plugins/mods that are running on your server which might add additional data.  You can also find more information in the github docs (https:/github.com/Valandur/Web-API/tree/master/docs/DATA.md) 
 *
 * OpenAPI spec version: <version>
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.WorldFullDimensionType;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * WorldFullDimension
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-09T21:04:49.224+02:00")
public class WorldFullDimension {
  @SerializedName("type")
  private WorldFullDimensionType type = null;

  @SerializedName("height")
  private BigDecimal height = null;

  @SerializedName("buildHeight")
  private BigDecimal buildHeight = null;

  public WorldFullDimension type(WorldFullDimensionType type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public WorldFullDimensionType getType() {
    return type;
  }

  public void setType(WorldFullDimensionType type) {
    this.type = type;
  }

  public WorldFullDimension height(BigDecimal height) {
    this.height = height;
    return this;
  }

   /**
   * The height of the dimension.
   * @return height
  **/
  @ApiModelProperty(value = "The height of the dimension.")
  public BigDecimal getHeight() {
    return height;
  }

  public void setHeight(BigDecimal height) {
    this.height = height;
  }

  public WorldFullDimension buildHeight(BigDecimal buildHeight) {
    this.buildHeight = buildHeight;
    return this;
  }

   /**
   * The maximum allowed build height of the dimension.
   * @return buildHeight
  **/
  @ApiModelProperty(value = "The maximum allowed build height of the dimension.")
  public BigDecimal getBuildHeight() {
    return buildHeight;
  }

  public void setBuildHeight(BigDecimal buildHeight) {
    this.buildHeight = buildHeight;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorldFullDimension worldFullDimension = (WorldFullDimension) o;
    return Objects.equals(this.type, worldFullDimension.type) &&
        Objects.equals(this.height, worldFullDimension.height) &&
        Objects.equals(this.buildHeight, worldFullDimension.buildHeight);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, height, buildHeight);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorldFullDimension {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    buildHeight: ").append(toIndentedString(buildHeight)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

