/**
 * WebAPI
 * Access Sponge powered Minecraft servers through a WebAPI  #/ Introduction This is the documentation of the various API routes offered by the WebAPI plugin.  This documentation assumes that you are familiar with the basic concepts of Web API's, such as `GET`, `PUT`, `POST` and `DELETE` methods, request `HEADERS` and `RESPONSE CODES` and `JSON` data.  By default this documentation can be found at http:/localhost:8080 (while your minecraft server is running) and the various routes start with http:/localhost:8080/api/...  As a quick test try reaching the route http:/localhost:8080/api/info (remember that you can only access \"localhost\" routes on the server on which you are running minecraft). This route should show you basic information about your server, like the motd and player count.  #/ Additional data Certain endpoints (such as `/player`, `/entity` and `/tile-entity` have additional properties which are not documented here, because the data depends on the concrete object type (eg. `Sheep` have a wool color, others do not) and on the other plugins/mods that are running on your server which might add additional data.  You can also find more information in the github docs (https:/github.com/Valandur/Web-API/tree/master/docs/DATA.md) 
 *
 * OpenAPI spec version: <version>
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ExecuteCommandResponse;
import io.swagger.client.model.CommandRequest;
import io.swagger.client.model.InlineResponse403;
import io.swagger.client.model.CommandResponse1;
import io.swagger.client.model.CommandsResponse;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CommandApi
 */
public class CommandApiTest {

    private final CommandApi api = new CommandApi();

    
    /**
     * Execute command
     *
     * Execute a command on the server. (Almost the same as running it from the console). Pass a list of commands to execute them in succession, if only passing one command the array is not required.  &gt; Required permission: cmd.run &gt; Required permission: cmd.run.[command] 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void executeCommandTest() throws ApiException {
        List<CommandRequest> request = null;
        // ExecuteCommandResponse response = api.executeCommand(request);

        // TODO: test validations
    }
    
    /**
     * Detailed command info
     *
     * Get detailed information about a command.  &gt; Required permission: cmd.one 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCommandTest() throws ApiException {
        String name = null;
        // CommandResponse1 response = api.getCommand(name);

        // TODO: test validations
    }
    
    /**
     * Command list
     *
     * Gets a list of all the commands available on the server.  &gt; Required permission: cmd.list 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCommandsTest() throws ApiException {
        // CommandsResponse response = api.getCommands();

        // TODO: test validations
    }
    
}
