/*
 * WebAPI
 * Access Sponge powered Minecraft servers through a WebAPI  # Introduction This is the documentation of the various API routes offered by the WebAPI plugin.  This documentation assumes that you are familiar with the basic concepts of Web API's, such as `GET`, `PUT`, `POST` and `DELETE` methods, request `HEADERS` and `RESPONSE CODES` and `JSON` data.  By default this documentation can be found at http:/localhost:8080 (while your minecraft server is running) and the various routes start with http:/localhost:8080/api/...  As a quick test try reaching the route http:/localhost:8080/api/info (remember that you can only access \"localhost\" routes on the server on which you are running minecraft). This route should show you basic information about your server, like the motd and player count.  # Additional data Certain endpoints (such as `/player`, `/entity` and `/tile-entity` have additional properties which are not documented here, because the data depends on the concrete object type (eg. `Sheep` have a wool color, others do not) and on the other plugins/mods that are running on your server which might add additional data.  You can also find more information in the github docs (https:/github.com/Valandur/Web-API/tree/master/docs/DATA.md) 
 *
 * OpenAPI spec version: <version>
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.InlineResponse400;
import io.swagger.client.model.NucleusJailResponse;
import io.swagger.client.model.NucleusJailsResponse;
import io.swagger.client.model.NucleusKitResponse;
import io.swagger.client.model.NucleusKitsResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for NucleusApi
 */
@Ignore
public class NucleusApiTest {

    private final NucleusApi api = new NucleusApi();

    
    /**
     * Detailed jail info
     *
     * Get detailed information about a jail.  &gt; Required permission: nucleus.jail.one 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getJailTest() throws ApiException {
        String name = null;
        NucleusJailResponse response = api.getJail(name);

        // TODO: test validations
    }
    
    /**
     * Jail list
     *
     * Get a list of all the jails on the server.  &gt; Required permission: nucleus.jail.list 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getJailsTest() throws ApiException {
        String details = null;
        NucleusJailsResponse response = api.getJails(details);

        // TODO: test validations
    }
    
    /**
     * Detailed kit info
     *
     * Get detailed information about a kit.  &gt; Required permission: nucleus.kit.one 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getKitTest() throws ApiException {
        String name = null;
        NucleusKitResponse response = api.getKit(name);

        // TODO: test validations
    }
    
    /**
     * Kit list
     *
     * Get a list of all the kits on the server.  &gt; Required permission: nucleus.kit.list 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getKitsTest() throws ApiException {
        String details = null;
        NucleusKitsResponse response = api.getKits(details);

        // TODO: test validations
    }
    
}
